// Offline shell of the installed app. GENERATED by vykresli_aplikaci.py —
// do not edit; CI compares this file with the generator.
// Network first, always: online the app is exactly the deployed site and the
// cache only answers when the network does not. /api/ is never touched —
// account data must not outlive a session in a cache.
const SKORAPKA = "skorapka-v1";
const PREDEM = ["/", "/styl.css", "/offline.html", "/manifest.webmanifest", "/ikona-192.png", "/ikona-512.png"];

self.addEventListener("install", (udalost) => {
  udalost.waitUntil(caches.open(SKORAPKA).then((c) => c.addAll(PREDEM)).then(() => self.skipWaiting()));
});

self.addEventListener("activate", (udalost) => {
  udalost.waitUntil(
    caches.keys()
      .then((klice) => Promise.all(klice.filter((k) => k !== SKORAPKA).map((k) => caches.delete(k))))
      .then(() => self.clients.claim())
  );
});

self.addEventListener("fetch", (udalost) => {
  const pozadavek = udalost.request;
  const adresa = new URL(pozadavek.url);
  if (pozadavek.method !== "GET" || adresa.origin !== self.location.origin || adresa.pathname.startsWith("/api/")) {
    return;
  }
  udalost.respondWith(
    fetch(pozadavek)
      .then((odpoved) => {
        if (odpoved.ok && PREDEM.includes(adresa.pathname)) {
          const kopie = odpoved.clone();
          caches.open(SKORAPKA).then((c) => c.put(pozadavek, kopie));
        }
        return odpoved;
      })
      .catch(() => caches.match(pozadavek).then((ulozena) =>
        ulozena || (pozadavek.mode === "navigate" ? caches.match("/offline.html") : Response.error())))
  );
});
